component "solaris-10-sparc-sysroot" do |pkg, settings, platform|
  pkg.version "2015.07.28"
  pkg.md5sum "4eed18c2ddcc609f2f404094ce539ce2"
  pkg.url "http://pl-build-tools.delivery.puppetlabs.net/solaris/10/solaris-10-sparc-sysroot.tar.gz"

  # The sysroot was generated by running (requires gtar)...
  # mkdir -p solaris-10-sparc-sysroot/usr
  # rsync -avg /lib solaris-10-sparc-sysroot/
  # rsync -avg /usr/lib /usr/include solaris-10-sparc-sysroot/usr/
  # Lots of manual cleanup in the sysroot of things like AdobeReader, firefox, thunderbird, etc
  # gtar -czf solaris-10-sparc-sysroot.tar.gz --owner=0 --group=0 solaris-10-sparc-sysroot
  sysroot_base = File.join(settings[:prefix], 'sysroot')
  pkg.directory sysroot_base

  pkg.install do
    [
      "mv lib #{sysroot_base}/",
      "mv usr #{sysroot_base}/",
    ]
  end
end
