component "solaris-10-sparc-sysroot" do |pkg, settings, platform|
  pkg.version "2015.07.28"
  pkg.md5sum "78a400a8bb81cbfe67b7c938b32ac60d"
  pkg.url "http://pl-build-tools.delivery.puppetlabs.net/solaris/10/solaris-10-sparc-sysroot.tar.gz"

  # The sysroot was generated by running (requires gtar)...
  # gtar --transform 's|^|solaris-10-sparc-sysroot/|' -czf solaris-10-sparc-sysroot.tar.gz /usr/lib /usr/include /lib
  sysroot_base = File.join(settings[:prefix], 'sysroot')
  pkg.directory sysroot_base

  pkg.install do
    [
      "mv lib #{sysroot_base}/",
      "mv usr #{sysroot_base}/",
    ]
  end
end
