component "sysroot" do |pkg, settings, platform|
  case platform.name
    when "debian-8-armhf"
      pkg.version "2016.05.18"
      pkg.md5sum "906c60e460ea848f49fb2885202d0f18"
    when "debian-8-armel"
      pkg.version "2016.09.07"
      pkg.md5sum "d08a22cd4f431d4e1fc0d1869f60d9da"
    when "el-7-aarch64"
      pkg.version "2017.06.13"
      pkg.md5sum "b1cb6fc6253a2bbb5cc17fda16ec64ae"
    when "el-6-s390x"
      pkg.version "2016.05.23"
      pkg.md5sum "e08bc4f2a5cfb39033ee138fd22bd7f2"
    when "el-7-s390x"
      pkg.version "2016.07.29"
      pkg.md5sum "8ce88d3df4c2c7f8a39ec46b0d78d88c"
    when "el-7-ppc64le"
      pkg.version "2016.05.15"
      pkg.md5sum "5a31e65abf83ff077dd8bac797f193f4"
    when "huaweios-6-powerpc"
      pkg.version "2016.02.08"
      pkg.md5sum "82589b28efdc5ccf6181499c4f49a1ac"
    when "ubuntu-16.04-ppc64el"
      pkg.version "2017.03.27"
      pkg.md5sum "60c71cf24c8ff1694e6a540133075fd9"
    when "sles-11-s390x"
      pkg.version "2016.04.12"
      pkg.md5sum "f719aabd9f3d180a70bcc88680bd4ada"
    when "sles-12-s390x"
      pkg.version "2016.05.02"
      pkg.md5sum "834b30ae19f7f8c30aa579b65f987f3a"
    when "sles-12-ppc64le"
      pkg.version "2017.08.21"
      pkg.md5sum "90edf955953e38fe72356ade7296cd21"
    when "solaris-10-sparc"
      pkg.version "2015.07.28"
      pkg.md5sum "4eed18c2ddcc609f2f404094ce539ce2"
    when "solaris-11-sparc"
      pkg.version "2015.09.09"
      pkg.md5sum "4edff510767d114bde1419743bc34d69"
  end

  if platform.is_cross_compiled?
    pkg.url "http://buildsources.delivery.puppetlabs.net/#{platform.name}-sysroot.tar.gz"
  end

  # The solaris sysroot was generated by running (requires gtar)...
  # mkdir -p solaris-10-sparc-sysroot/usr
  # rsync -avg /lib solaris-10-sparc-sysroot/
  # rsync -avg /usr/lib /usr/include solaris-10-sparc-sysroot/usr/
  # Lots of manual cleanup in the sysroot of things like AdobeReader, firefox, thunderbird, etc
  # gtar -czf solaris-10-sparc-sysroot.tar.gz --owner=0 --group=0 solaris-10-sparc-sysroot
  sysroot_base = File.join(settings[:prefix], 'sysroot')
  pkg.directory sysroot_base
  puts "sysroot base is " + sysroot_base

  libdirs = "lib"
  libdirs = "lib lib64" if platform.architecture == "s390x" || platform.name =~ /el-7-ppc64le|sles-12-ppc64le/ || platform.architecture == "aarch64"
  pkg.install do
    [
      "mv #{libdirs} #{sysroot_base}/",
      "mv usr #{sysroot_base}/",
    ]
  end
end
