component "sysroot" do |pkg, settings, platform|
  case platform.name
    when "el-7-aarch64"
      pkg.version "2017.06.13"
      pkg.md5sum "b1cb6fc6253a2bbb5cc17fda16ec64ae"
    when "el-7-ppc64" # Centos 7.5 - Infrastructure Server Install
      pkg.version "2018.09.14"
      pkg.md5sum "9aa45667c6b265fd2f356ee650bf0e27"
    when "el-7-ppc64le"
      pkg.version "2016.05.15"
      pkg.md5sum "5a31e65abf83ff077dd8bac797f193f4"
    when "huaweios-6-powerpc"
      pkg.version "2016.02.08"
      pkg.md5sum "82589b28efdc5ccf6181499c4f49a1ac"
    when "sles-12-ppc64le"
      pkg.version "2017.08.21"
      pkg.md5sum "90edf955953e38fe72356ade7296cd21"
    when "solaris-10-sparc"
      pkg.version "2015.07.28"
      pkg.md5sum "4eed18c2ddcc609f2f404094ce539ce2"
    when "solaris-11-sparc"
      pkg.version "2015.09.09"
      pkg.md5sum "4edff510767d114bde1419743bc34d69"
  end

  if platform.is_cross_compiled?
    pkg.url "#{settings[:buildsources_url]}/#{platform.name}-sysroot.tar.gz"
  end

  # The solaris sysroot was generated by running (requires gtar)...
  # mkdir -p solaris-10-sparc-sysroot/usr
  # rsync -avg /lib solaris-10-sparc-sysroot/
  # rsync -avg /usr/lib /usr/include solaris-10-sparc-sysroot/usr/
  # Lots of manual cleanup in the sysroot of things like AdobeReader, firefox, thunderbird, etc
  # gtar -czf solaris-10-sparc-sysroot.tar.gz --owner=0 --group=0 solaris-10-sparc-sysroot
  sysroot_base = File.join(settings[:prefix], 'sysroot')
  pkg.directory sysroot_base
  puts "sysroot base is " + sysroot_base

  libdirs = "lib"
  libdirs = "lib lib64" if platform.name =~ /el-7-ppc64|sles-12-ppc64le/ || platform.architecture == "aarch64"
  pkg.install do
    [
      "mv #{libdirs} #{sysroot_base}/",
      "mv usr #{sysroot_base}/",
    ]
  end
end
